# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interface

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class _MethodResponseSuccess(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = _MethodResponseSuccess()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAs_MethodResponseSuccess(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # _MethodResponseSuccess
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # _MethodResponseSuccess
    def Resources(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from meillionen.interface._Resource import _Resource
            obj = _Resource()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # _MethodResponseSuccess
    def ResourcesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # _MethodResponseSuccess
    def ResourcesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def _MethodResponseSuccessStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddResources(builder, resources): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(resources), 0)
def _MethodResponseSuccessAddResources(builder, resources):
    """This method is deprecated. Please switch to AddResources."""
    return AddResources(builder, resources)
def StartResourcesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def _MethodResponseSuccessStartResourcesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartResourcesVector(builder, numElems)
def End(builder): return builder.EndObject()
def _MethodResponseSuccessEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)