# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interface

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class _MethodResponseError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = _MethodResponseError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAs_MethodResponseError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # _MethodResponseError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # _MethodResponseError
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # _MethodResponseError
    def Trace(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(2)
def _MethodResponseErrorStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def _MethodResponseErrorAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def AddTrace(builder, trace): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(trace), 0)
def _MethodResponseErrorAddTrace(builder, trace):
    """This method is deprecated. Please switch to AddTrace."""
    return AddTrace(builder, trace)
def End(builder): return builder.EndObject()
def _MethodResponseErrorEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)