# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interface

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class _ModuleInterface(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = _ModuleInterface()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAs_ModuleInterface(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # _ModuleInterface
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # _ModuleInterface
    def Classes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from meillionen.interface._ClassInterface import _ClassInterface
            obj = _ClassInterface()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # _ModuleInterface
    def ClassesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # _ModuleInterface
    def ClassesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def _ModuleInterfaceStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddClasses(builder, classes): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(classes), 0)
def _ModuleInterfaceAddClasses(builder, classes):
    """This method is deprecated. Please switch to AddClasses."""
    return AddClasses(builder, classes)
def StartClassesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def _ModuleInterfaceStartClassesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartClassesVector(builder, numElems)
def End(builder): return builder.EndObject()
def _ModuleInterfaceEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)