# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import module_model_service_pb2 as module__model__service__pb2


class ModuleModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.apply = channel.stream_stream(
                '/ModuleModelService/apply',
                request_serializer=module__model__service__pb2.Request.SerializeToString,
                response_deserializer=module__model__service__pb2.Response.FromString,
                )


class ModuleModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def apply(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'apply': grpc.stream_stream_rpc_method_handler(
                    servicer.apply,
                    request_deserializer=module__model__service__pb2.Request.FromString,
                    response_serializer=module__model__service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModuleModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModuleModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def apply(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ModuleModelService/apply',
            module__model__service__pb2.Request.SerializeToString,
            module__model__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
