# Book settings
title: "Meillionen"
author: Open Modeling Foundation
logo: logo.png

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button:

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/openmodelingfoundation/meillionen
  path_to_book: meillionen-docs

sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
