name: Test Meillionen Packages

on:
  push:
    branches:
      - main

jobs:
  test-packages:
    name: Test Python Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: python/environment.yml
      - name: Activate environment
        run: |
          conda info
          conda list
          conda env list
      - name: Install packages
        shell: bash -l {0}
        run: |
          cd python
          poetry install
          cd -
          cd examples/crop-pipeline/simplecrop
          poetry install
          cd ../overlandflow
          poetry install
      - name: Test packages
        shell: bash -l {0}
        run: |
          cd python
          poetry run pytest
          cd ../examples/crop-pipeline/simplecrop
          poetry run pytest
          cd ../overlandflow
          poetry run pytest
      - name: Build docs
        shell: bash -l {0}
        run: |
          cd docs
          jupyter book build .
