name: Test Meillionen Packages

on:
  push:
    branches:
      - staging

jobs:
  test-packages:
    name: Test Python Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: meillionen
          environment-file: python/environment.yml
      - name: Install packages
        run: |
          cd python
          poetry install
          cd -
          cd examples/crop-pipeline/simplecrop
          poetry install
          cd ../overlandflow
          poetry install
      - name: Test packages
        run: |
          cd python
          poetry run pytest
          cd ../examples/crop-pipeline/simplecrop
          poetry run pytest
          cd ../overlandflow
          poetry run pytest
      - name: Build docs
        run: |
          cd docs
          jupyter book build .